
version: '3'

networks:
  laravel-project:
services:
  webserver:
    image: nginx:latest
    ports:
      - "8009:80"
    volumes:
      - ./.server.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./.env:/var/www/.env
      - ./artisan:/var/www/artisan
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpunit.xml:/var/www/phpunit.xml
    depends_on:
      - php-fpm
      - database
    networks:
      - laravel-project
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - laravel-project
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./.env:/var/www/.env
      - ./artisan:/var/www/artisan
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpunit.xml:/var/www/phpunit.xml
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"
  database:
    image: postgres:latest
    ports:
      - "54321:5432"
    networks:
      - laravel-project
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}